analyzer:
  errors:
    no_runtimetype_tostring: ignore
    avoid_catches_without_on_clauses: ignore
include: package:very_good_analysis/analysis_options.yaml
linter:
  rules:
    avoid_types_on_closure_parameters: true
    public_member_api_docs: false
    specify_nonobvious_property_types: false
    one_member_abstracts: false
